- hosts: all
  vars_files:
        dvd_dir: “/dvd”
        http_port: 80
  tasks:
     - name: “creating directory”
       file:
          state: directory
          path: “{{ dvd_dir }}”


     - name: “Mount the DVD over directory”
       mount:
          src: “/dev/cdrom”
          path: “{{dvd_dir}}”
          state: mount
          fstype: “iso9960”


     - name: “Yum configuration for Appstream”
       yum_repository:
          baseurl: “{{dvd_dir}}/AppStream”
          name: “/dvd1”
          description: “dvd1 for AppStream package”
          gpgcheck: no
        

     - name: “Yum configuration for BaseOS”
       yum_repository:
          baseurl: “{{dvd_dir}}/BaseOS”
          name: “/dvd2”
          description: “dvd2 for BaseOS package”
          gpgcheck: no


     - name: "HTTPD Installation"
       package:
          name: “httpd”
          state: present

    
     - name: "Copying conf file"
       template:
          dest: "/etc/httpd/conf.d/myhttpd.conf"
          src: "myhttpd.conf"
       notify:
          - changed
     

     - name: "Firewall enabling"
       firewalled:
          port: “{{http_port}}/tcp”
          state: enabled
          immediate: yes
          permanent: yes


     - name: "Service starting"
       service:
          name: "httpd"
          state: started
